```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tximport))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(ggvenn)) #from dev tools
suppressPackageStartupMessages(library(ggVennDiagram))

source("/project/imoskowitz/shared/software/helper_functions/carlosFunc_3.R")
source("/project/imoskowitz/shared/software/helper_functions/rowr.R")


RC1_RC7_combat <- readRDS("./data/dds_RC1_RC7_combat.rds")
RC1_RC7_DESeq2 <- readRDS("./data/dds_RC1_RC7_DESeq2_batch_correction.rds")


```

```{r}

res_D6_dox_vs_D6_ctrl_combat <- get_deseq_results(RC1_RC7_combat,
    contrast = "time_condition", 
    treatment = "D6_dox",
    control = "D6_ctrl")

res_D6_dox_vs_D6_ctrl_DESeq2 <- get_deseq_results(RC1_RC7_DESeq2,
    contrast = "time_condition", 
    treatment = "D6_dox",
    control = "D6_ctrl")

up_list <- list(combat_D6 = subset(res_D6_dox_vs_D6_ctrl_combat, padj < 0.05 & log2FoldChange > 0)$gene_id,
                DESeq2_D6 = subset(res_D6_dox_vs_D6_ctrl_DESeq2, padj < 0.05 & log2FoldChange > 0)$gene_id)

down_list <- list(combat_D6 = subset(res_D6_dox_vs_D6_ctrl_combat, padj < 0.05 & log2FoldChange < 0)$gene_id,
                DESeq2_D6 = subset(res_D6_dox_vs_D6_ctrl_DESeq2, padj < 0.05 & log2FoldChange < 0)$gene_id)


ggvenn(up_list, 
       show_percentage = FALSE,
       fill_color = c("#0073C2FF", "#EFC000FF"),
       stroke_size = 0,
       text_size = 10,
       padding = 0.2,
       set_name_size = 8)

ggsave(filename = "venn_D6_upgenes_combat_vs_DESeq2.pdf",
    plot = last_plot(),
    device = "pdf",
    width = 5.5, height = 5.5,
    path = "pdfs")
dev.off()

ggvenn(down_list, 
       show_percentage = FALSE,
       fill_color = c("#0073C2FF", "#EFC000FF"),
       stroke_size = 0,
       text_size = 10,
       padding = 0.2,
       set_name_size = 8)

ggsave(filename = "venn_D6_downgenes_combat_vs_DESeq2.pdf",
    plot = last_plot(),
    device = "pdf",
    width = 5.5, height = 5.5,
    path = "pdfs")
dev.off()



tmp_up <- ggVennDiagram::process_region_data(ggVennDiagram::Venn(up_list))
tmp_list_up <- tmp_up$item

for(i in 1:length(tmp_list_up)) {
    names(tmp_list_up)[i] <- tmp_up$name[i]
}

cbind.fill(fill = NA,
tmp_list_up$combat_D6,
tmp_list_up$DESeq2_D6) |>
      set_names("combat_D6_unique", "DESeq2_D6_unique") |>
      data.frame() %>%
      write_csv("data/tmp_up_D6_combat_unique_vs_DESeq2_unique.csv")

##down 
tmp_down <- ggVennDiagram::process_region_data(ggVennDiagram::Venn(down_list))
tmp_list_down <- tmp_down$item

for(i in 1:length(tmp_list_down)) {
    names(tmp_list_down)[i] <- tmp_down$name[i]
}

cbind.fill(fill = NA,
tmp_list_down$combat_D6,
tmp_list_down$DESeq2_D6) |>
      set_names("combat_D6_unique", "DESeq2_D6_unique") |>
      data.frame() %>%
      write_csv("data/tmp_down_D6_combat_unique_vs_DESeq2_unique.csv")





## try D8

res_D8_dox_vs_D8_ctrl_combat <- get_deseq_results(RC1_RC7_combat,
    contrast = "time_condition", 
    treatment = "D8_dox",
    control = "D8_ctrl")    

res_D8_dox_vs_D8_ctrl_DESeq2 <- get_deseq_results(RC1_RC7_DESeq2,
    contrast = "time_condition", 
    treatment = "D8_dox",
    control = "D8_ctrl")    

up_list <- list(combat_D8 = subset(res_D8_dox_vs_D8_ctrl_combat, padj < 0.05 & log2FoldChange > 0)$gene_id,
                DESeq2_D8 = subset(res_D8_dox_vs_D8_ctrl_DESeq2, padj < 0.05 & log2FoldChange > 0)$gene_id)

down_list <- list(combat_D8 = subset(res_D8_dox_vs_D8_ctrl_combat, padj < 0.05 & log2FoldChange < 0)$gene_id,
                DESeq2_D8 = subset(res_D8_dox_vs_D8_ctrl_DESeq2, padj < 0.05 & log2FoldChange < 0)$gene_id) 
    
ggvenn(up_list, 
       show_percentage = FALSE,
       fill_color = c("#17964c", "#871985"),
       stroke_size = 0,
       text_size = 10,
       padding = 0.2,
       set_name_size = 8)

ggsave(filename = "venn_D8_upgenes_combat_vs_DESeq2.pdf",
    plot = last_plot(),
    device = "pdf",
    width = 5.5, height = 5.5,
    path = "pdfs")
dev.off()

ggvenn(down_list, 
       show_percentage = FALSE,
       fill_color = c("#17964c", "#871985"),
       stroke_size = 0,
       text_size = 10,
       padding = 0.2,
       set_name_size = 8)

ggsave(filename = "venn_D8_downgenes_combat_vs_DESeq2.pdf",
    plot = last_plot(),
    device = "pdf",
    width = 5.5, height = 5.5,
    path = "pdfs")
dev.off()


tmp_up <- ggVennDiagram::process_region_data(ggVennDiagram::Venn(up_list))
tmp_list_up <- tmp_up$item

for(i in 1:length(tmp_list_up)) {
    names(tmp_list_up)[i] <- tmp_up$name[i]
}

cbind.fill(fill = NA,
tmp_list_up$combat_D8,
tmp_list_up$DESeq2_D8) |>
      set_names("combat_D8_unique", "DESeq2_D8_unique") |>
      data.frame() %>%
      write_csv("data/tmp_up_D8_combat_unique_vs_DESeq2_unique.csv")

##down 
tmp_down <- ggVennDiagram::process_region_data(ggVennDiagram::Venn(down_list))
tmp_list_down <- tmp_down$item

for(i in 1:length(tmp_list_down)) {
    names(tmp_list_down)[i] <- tmp_down$name[i]
}

cbind.fill(fill = NA,
tmp_list_down$combat_D8,
tmp_list_down$DESeq2_D8) |>
      set_names("combat_D8_unique", "DESeq2_D8_unique") |>
      data.frame() %>%
      write_csv("data/tmp_down_D8_combat_unique_vs_DESeq2_unique.csv")









```

